"""Tests for data extraction logic in scripts.prepare_data.

Focuses on properties that prevent silent data bugs:
- IND extraction must combine control + treatment records
- Extracted data must not be trivially solvable by label mapping
- Record fields are correctly populated
"""

import json
from pathlib import Path

from scripts.prepare_data import (
    _find_control_opponent,
    _run_all_extractions,
    run_extraction,
    sample_to_training_record,
)

# --- Fixtures: synthetic eval samples ---


def _make_ind_sample(
    uuid: str,
    is_control: bool,
    correct_answer: str,
    response_text: str = "Some response",
    dataset: str = "sharegpt",
    opponent: str = "qwen-2.5-7b",
):
    """Create a synthetic IND eval sample matching the Inspect format."""
    if is_control:
        treatment_name = "ll-3.1-8b"
    else:
        treatment_name = opponent

    # Simulate the label randomization from self-rec-framework:
    # correct_answer is which number means the right thing
    if correct_answer == "1":
        instruction = (
            'Answer "1" if this is your original output, or "2" if it was '
            "generated by a different language model."
        )
    else:
        instruction = (
            'Answer "2" if this is your original output, or "1" if it was '
            "generated by a different language model."
        )

    prompt = (
        f"Below is a user request followed by a response:\n\n"
        f"Request - \"test question\"\n\n"
        f"Response - \"{response_text}\"\n\n"
        f"Is this response your original output? {instruction} "
        f"Provide only the number and no additional text."
    )

    return {
        "input": prompt,
        "target": correct_answer,
        "metadata": {
            "uuid": uuid,
            "treatment_name": treatment_name,
            "is_control": is_control,
            "correct_answer": correct_answer,
            "dataset_name": dataset,
            "data_subset": "test_split",
        },
    }


def _make_pw_sample(
    uuid: str,
    correct_answer: str,
    opponent: str = "qwen-2.5-7b",
    dataset: str = "sharegpt",
):
    """Create a synthetic PW eval sample."""
    return {
        "input": f"Which response is yours? Answer {correct_answer}.",
        "target": correct_answer,
        "metadata": {
            "uuid": uuid,
            "treatment_name_1": "ll-3.1-8b",
            "treatment_name_2": opponent,
            "correct_answer": correct_answer,
            "dataset_name": dataset,
            "data_subset": "test_split",
        },
    }


def _write_eval_dir(tmp_path: Path, samples: list[dict], name: str = "eval1") -> Path:
    """Write synthetic samples to an eval directory structure."""
    eval_dir = tmp_path / name
    samples_dir = eval_dir / "samples"
    samples_dir.mkdir(parents=True)
    for i, sample in enumerate(samples):
        with open(samples_dir / f"{i}_epoch_1.json", "w") as f:
            json.dump(sample, f)
    return eval_dir


# --- Tests for sample_to_training_record ---


class TestSampleToTrainingRecord:
    def test_ind_treatment_has_is_control_false(self):
        sample = _make_ind_sample("id1", is_control=False, correct_answer="1")
        record = sample_to_training_record(sample)
        assert record["is_control"] is False
        assert record["format"] == "ind"

    def test_ind_control_has_is_control_true(self):
        sample = _make_ind_sample("id1", is_control=True, correct_answer="2")
        record = sample_to_training_record(sample)
        assert record["is_control"] is True
        assert record["format"] == "ind"

    def test_ind_preserves_dataset(self):
        sample = _make_ind_sample("id1", is_control=False, correct_answer="1",
                                  dataset="wikisum")
        record = sample_to_training_record(sample)
        assert record["dataset"] == "wikisum"
        assert record["data_subset"] == "test_split"

    def test_pw_has_no_is_control(self):
        sample = _make_pw_sample("id1", "1")
        record = sample_to_training_record(sample)
        assert "is_control" not in record
        assert record["format"] == "pw"


# --- Tests for _find_control_opponent ---


class TestFindControlOpponent:
    def test_finds_control(self):
        groups = {
            "qwen-2.5-7b-treatment": {"sharegpt": []},
            "ll-3.1-8b-control": {"sharegpt": []},
        }
        assert _find_control_opponent(groups) == "ll-3.1-8b-control"

    def test_no_control(self):
        groups = {"qwen-2.5-7b": {"sharegpt": []}}
        assert _find_control_opponent(groups) is None


# --- Tests for IND extraction combining control + treatment ---


class TestINDExtractionMerge:
    """Tests that IND extraction combines control and treatment data."""

    def test_ind_extraction_includes_both_control_and_treatment(self, tmp_path):
        """The critical test: IND data must have both is_control=True and False."""
        # Create treatment samples (response from opponent)
        treatment_samples = [
            _make_ind_sample("id1", is_control=False, correct_answer="1",
                             response_text="opponent wrote this"),
            _make_ind_sample("id1", is_control=False, correct_answer="2",
                             response_text="opponent wrote this"),
        ]
        # Create control samples (response from self)
        control_samples = [
            _make_ind_sample("id2", is_control=True, correct_answer="1",
                             response_text="I wrote this"),
            _make_ind_sample("id2", is_control=True, correct_answer="2",
                             response_text="I wrote this"),
        ]

        treatment_dir = _write_eval_dir(tmp_path, treatment_samples, "treatment")
        control_dir = _write_eval_dir(tmp_path, control_samples, "control")

        output_dir = tmp_path / "output"
        run_extraction(
            [treatment_dir, control_dir],
            fmt="ind",
            output_dir=output_dir,
            train_ratio=1.0,  # all to train for simplicity
        )

        with open(output_dir / "train.jsonl") as f:
            records = [json.loads(line) for line in f]

        controls = [r for r in records if r.get("is_control")]
        treatments = [r for r in records if not r.get("is_control")]
        assert len(controls) > 0, "IND data must include control records"
        assert len(treatments) > 0, "IND data must include treatment records"

    def test_ind_not_trivially_solvable(self, tmp_path):
        """IND data must not be solvable by just reading the label mapping.

        If all records have the same is_control value, the correct answer
        is always the same semantic choice ("mine" or "not mine"), making
        the task trivially solvable by parsing the instruction.
        """
        # Create mixed samples
        samples = [
            _make_ind_sample("id1", is_control=False, correct_answer="1",
                             response_text="opponent response"),
            _make_ind_sample("id1", is_control=False, correct_answer="2",
                             response_text="opponent response"),
            _make_ind_sample("id2", is_control=True, correct_answer="1",
                             response_text="self response"),
            _make_ind_sample("id2", is_control=True, correct_answer="2",
                             response_text="self response"),
        ]

        eval_dir = _write_eval_dir(tmp_path, samples)
        output_dir = tmp_path / "output"
        run_extraction(
            [eval_dir], fmt="ind", output_dir=output_dir, train_ratio=1.0,
        )

        with open(output_dir / "train.jsonl") as f:
            records = [json.loads(line) for line in f]

        # For each label mapping direction, both correct answers should appear.
        # If target is always the same for a given instruction pattern,
        # the task is trivially solvable.
        #
        # Records where "1" = own output: some should have target=1 (control),
        # some should have target=2 (treatment, so "not mine" = 2)
        # This ensures the model must read the RESPONSE, not just the instruction.
        targets_by_control = {}
        for r in records:
            key = r.get("is_control", False)
            targets_by_control.setdefault(key, set()).add(r["target"])

        assert "1" in targets_by_control[True] and "2" in targets_by_control[True], (
            "Control records should have both targets (due to label randomization)"
        )
        assert "1" in targets_by_control[False] and "2" in targets_by_control[False], (
            "Treatment records should have both targets (due to label randomization)"
        )

    def test_run_all_extractions_merges_control_for_ind(self, tmp_path):
        """_run_all_extractions merges control dirs into each treatment group."""
        # Create enough IDs so both control and treatment appear in train split
        # (default train_ratio=0.8, so with 10 IDs we get 8 in train)
        treatment_samples = []
        for i in range(5):
            treatment_samples.append(
                _make_ind_sample(f"treat_{i}", is_control=False, correct_answer="1",
                                 response_text=f"opponent response {i}")
            )
            treatment_samples.append(
                _make_ind_sample(f"treat_{i}", is_control=False, correct_answer="2",
                                 response_text=f"opponent response {i}")
            )
        control_samples = []
        for i in range(5):
            control_samples.append(
                _make_ind_sample(f"ctrl_{i}", is_control=True, correct_answer="1",
                                 response_text=f"self response {i}")
            )
            control_samples.append(
                _make_ind_sample(f"ctrl_{i}", is_control=True, correct_answer="2",
                                 response_text=f"self response {i}")
            )
        treatment_dir = _write_eval_dir(tmp_path, treatment_samples, "treatment")
        control_dir = _write_eval_dir(tmp_path, control_samples, "control")

        by_experiment = {
            "ICML_02_UT_IND-Q_Rec_NPr_FA_Inst": {
                "qwen-2.5-7b-treatment": {"sharegpt": [treatment_dir]},
                "ll-3.1-8b-control": {"sharegpt": [control_dir]},
            }
        }

        output_base = tmp_path / "training_data"
        _run_all_extractions(
            by_experiment, "ll-3.1-8b", None, cot=False,
            output_base=output_base,
        )

        # Should create merged output (not separate control dir)
        output_dirs = list(output_base.glob(
            "ll-3.1-8b_ICML_02*qwen*sharegpt"
        ))
        assert len(output_dirs) == 1, f"Expected 1 output dir, got {output_dirs}"

        # Combine train + val to check all records
        records = []
        for fname in ["train.jsonl", "val.jsonl"]:
            with open(output_dirs[0] / fname) as f:
                records.extend(json.loads(line) for line in f)

        controls = [r for r in records if r.get("is_control")]
        treatments = [r for r in records if not r.get("is_control")]
        assert len(controls) > 0, "Merged data must include controls"
        assert len(treatments) > 0, "Merged data must include treatments"

        # No separate control output dir should exist
        control_dirs = list(output_base.glob(
            "ll-3.1-8b_ICML_02*control*"
        ))
        assert len(control_dirs) == 0, (
            f"Control should be merged, not separate: {control_dirs}"
        )

    def test_pw_extraction_unaffected_by_ind_merge(self, tmp_path):
        """PW extraction should not be affected by the IND control merge."""
        pw_samples = [
            _make_pw_sample("id1", "1"),
            _make_pw_sample("id1", "2"),
        ]
        eval_dir = _write_eval_dir(tmp_path, pw_samples)
        output_dir = tmp_path / "output"
        run_extraction(
            [eval_dir], fmt="pw", output_dir=output_dir, train_ratio=1.0,
        )

        with open(output_dir / "train.jsonl") as f:
            records = [json.loads(line) for line in f]

        assert len(records) == 2
        assert all("is_control" not in r for r in records)
